version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.15.3
    working_directory: ~/dorsha
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
              echo "Installing latest npm"
              sudo npm install npm@latest -g

              echo "Installing bower and grunt-cli"
              sudo npm install -g bower grunt-cli

              echo "Running npm install"
              npm install

              echo "Running bower install"
              bower install
      - run:
          name: Build
          command: grunt build
      - run:
          name: Test
          command: |
              npm run lint
              npm run coverage
      - run:
          name: Deploy
          command: |
              echo CircleCI tag is: $CIRCLE_TAG
              if [[ $CIRCLE_TAG =~ master ]]; then
                ./node_modules/.bin/firebase deploy --token $FIREBASE_TOKEN
              else
                echo 'Nothing to do.'
              fi
