name: Issue Guard

on:
  issues:
    types: [opened, closed, reopened]

jobs:
  check-labels:
    runs-on: ubuntu-latest
    name: Check issue contains relevant label
    steps:
      - if: |
          ${{ (github.event.issue.opened || github.event.issue.reopened) }} && join(github.event.issue.labels.*.name, '') == ''
        name: Close issue if has no labels
        uses: peter-evans/close-issue@v2
        with:
          comment: |
            Issue must have labels. Auto-closing this issue.
      # - name: Re-open if closing labels not presented
      #   uses: hramos/label-actions@v1
      #   with:
      #     repo-token: ${{ secrets.GITHUB_TOKEN }}
      #     reopen: github.event.issue.closed && contains(github.event.issue.labels.*.name, 'cannot-reproduce', 'duplicate', 'invalid', 'question', 'wontfix')
      #     comment: |
      #       Missing closing label
      # - name: Add documentation label in case bug, enhancement or security issue got closed
      #   uses: hramos/label-actions@v1
      #   with:
      #     repo-token: ${{ secrets.GITHUB_TOKEN }}
      #     labels: documentation
      #     perform: github.event.issue.closed && contains(github.event.issue.labels.*.name, 'bug', 'enhancement', 'security', 'securityvulnerability')
      #     comment: |
      #       Require documentation
