name: Issue Guard - close

on:
  issues:
    types: [closed]

jobs:
  check-labels:
    runs-on: ubuntu-latest
    name: Check closed issue
    steps:
      - name: View context attributes
        uses: actions/github-script@v6
        with:
          script: console.log(JSON.Stringify(${{github.event}}))
      - if: "!contains(github.event.issue.labels.*.name, 'documentation') && (contains(github.event.issue.labels.*.name, 'bug') || contains(github.event.issue.labels.*.name, 'enhancement')  || contains(github.event.issue.labels.*.name, 'security') || contains(github.event.issue.labels.*.name, 'securityvulnerability'))"
        name: Add documentation label for closed issue if needed
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ["documentation"],
              title: "[Documentation] - ${{github.event.issue.title}}",
              body: "Documentation issue for: ${{github.event.issue.url}}"
            })
      # - name: Re-open if closing labels not presented
      #   uses: hramos/label-actions@v1
      #   with:
      #     repo-token: ${{ secrets.GITHUB_TOKEN }}
      #     reopen: github.event.issue.closed && contains(github.event.issue.labels.*.name, 'cannot-reproduce', 'duplicate', 'invalid', 'question', 'wontfix')
      #     comment: |
      #       Missing closing label
