name: Issue Guard - close

on:
  issues:
    types: [closed]

jobs:
  check-labels:
    runs-on: ubuntu-latest
    name: Check closed issue
    steps:
      - name: Get linked pull requests
        uses: FujiHaruka/issue-refs-parser-action@v1.1
        id: action
        with:
          body: ${{ github.event.comment.body }}
      - name: List linked pull requests
        run: |
          echo "refs: ${{ steps.action.outputs.refs }}"
          echo "external_refs: ${{ steps.action.outputs.external_refs }}"
      - if: "!contains(github.event.issue.labels.*.name, 'cannot-reproduce') && !contains(github.event.issue.labels.*.name, 'duplicate') && !contains(github.event.issue.labels.*.name, 'invalid') && !contains(github.event.issue.labels.*.name, 'question') && !contains(github.event.issue.labels.*.name, 'wontfix') && !contains(github.event.issue.labels.*.name, 'documentation') && !contains(github.event.issue.labels.*.name, 'documentation-linked') && (contains(github.event.issue.labels.*.name, 'bug') || contains(github.event.issue.labels.*.name, 'enhancement')  || contains(github.event.issue.labels.*.name, 'security') || contains(github.event.issue.labels.*.name, 'securityvulnerability'))"
        name: Add documentation label for closed issue if needed
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ["documentation-linked"]
            })
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ["documentation"],
              title: "[Documentation] - ${{github.event.issue.title}}",
              body: "Documentation issue for: ${{github.event.issue.html_url}}"
            })
      - if: "!contains(github.event.issue.labels.*.name, 'cannot-reproduce') && !contains(github.event.issue.labels.*.name, 'duplicate') && !contains(github.event.issue.labels.*.name, 'invalid') && !contains(github.event.issue.labels.*.name, 'question') && !contains(github.event.issue.labels.*.name, 'wontfix') && !contains(github.event.issue.labels.*.name, 'documentation') && !contains(github.event.issue.labels.*.name, 'documentation-linked')"
        name: Reopen issue if not having closing labels
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.update({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: "open"
            })
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "Missing one of the closing labels: 'cannot-reproduce', 'duplicate', 'invalid', 'wontfix'"
            });
