name: Issue Guard

on:
  issues:
    types: [opened, closed]

jobs:
  check-labels:
    runs-on: ubuntu-latest
    name: Check closed issue contains relevant label
    steps:
      - uses: actions/checkout@v3
      - name: Re-open if closing labels not presented
        uses: hramos/label-actions@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          close: github.event.issue.opened && join(github.event.issue.labels) == ''
          comment: |
            Missing labels
      - name: Re-open if closing labels not presented
        uses: hramos/label-actions@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          reopen: github.event.issue.closed && contains(github.event.issue.labels.*.name, 'cannot-reproduce', 'duplicate', 'invalid', 'question', 'wontfix')
          comment: |
            Missing closing label
      - name: Add documentation label in case bug, enhancement or security issue got closed
        uses: hramos/label-actions@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          labels: documentation
          perform: github.event.issue.closed && contains(github.event.issue.labels.*.name, 'bug', 'enhancement', 'security', 'securityvulnerability')
          comment: |
            Require documentation
